# Generated by Django 4.0.2 on 2022-03-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.TextField()),
                ('change', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
